FROM plugins/base:windows-amd64

LABEL maintainer="Bo-Yi Wu <appleboy.tw@gmail.com>" \
  org.label-schema.name="Drone Apex Up" \
  org.label-schema.vendor="Bo-Yi Wu" \
  org.label-schema.schema-version="1.0"

COPY release/drone-apex-up.exe /drone-apex-up.exe

ENTRYPOINT [ "\\drone-apex-up.exe" ]
